### ISSUE TITLE
Missing required python3-policycoreutils package for RedHat

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-selinux#2]
## Describe the bug

The robertdebock.selinux role version 2.3.5 (pulled from Ansible Galaxy) is missing required python3-policycoreutils package in vars/main.yml for RedHat:

```yaml
  Amazon-2018: *rhel7
  RedHat:
    - python3-dnf
    - python3-libselinux
    - python3-libsemanage
    - python3-policycoreutils # <- NEW
``` 

This does NOT break the selinux role, but it can cause other roles to break.  For example, if I use robertdebug.selinux set to enforce, and then subsequently use the robertdebock.httpd role, the latter fails at:

```yaml
- name: modify selinux settings
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  loop: "{{ httpd_sebooleans }}"
```

because the Ansible seboolean module fails due to the missing policycoreutils package.

Thanks,

Jim Reuter
