### ISSUE TITLE
Not working in ansible 2.10

### ISSUE THREAD

**Issue by Chilinot** [robertdebock/ansible-role-selinux#4]
## Describe the bug
Running a playbook with the role leads to the following error:
```
ERROR! couldn't resolve module/action 'selinux'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '~/.ansible/roles/robertdebock.selinux/tasks/main.yml': line 12, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: manage selinux
  ^ here
```

## Playbook
```yaml
- name: Update system and enable SELinux
  become: true
  hosts: all
  roles:
    - role: robertdebock.selinux
      vars:
        selinux_state: enforcing
        selinux_policy: targeted
        # Should the machine be rebooted after changes?
        selinux_reboot: no
  tasks:
    - name: Update system
      command: yum upgrade -y
```

## Environment

- Control node OS: MacOS 19.6
- Control node Ansible version: 2.10.0
- Managed node OS: Amazon LInux 2
