### ISSUE TITLE
Conditional check for selinux_reboot incorrect

### ISSUE THREAD

**Issue by stdevel** [robertdebock/ansible-role-selinux#6]
## Describe the bug
It looks like the conditional check for `selinux_reboot` is incorrect. At least it's not working under Ansible 2.9.6+.

## Playbook

`requirements.yml`:
```yaml
---
roles:
  - name: robertdebock.selinux
    version: 2.6.1
```

`playbook.yml`:
```yaml
---
- name: Configure server
  hosts: HOSTNAME
  roles:
    - name: robertdebock.selinux
      selinux_state: enforcing
      selinux_reboot: false
```

## Output

```shell
TASK [robertdebock.selinux : test if selinux_reboot is set correctly] **********************************************************************************************************************************************
fatal: [HOSTNAME]: FAILED! => {"msg": "The conditional check 'selinux_reboot is bool' failed. The error was: template error while templating string: no test named 'bool'. String: {% if selinux_reboot is bool %} True {% else %} False {% endif %}"}
```

## Environment

- Control node OS: Pop!_OS 20.04 LTS
- Control node Ansible version: 2.9.6
- Managed node OS: CentOS 8.2.2004
